services: # Define the services that will be used in the pipeline
  terraform: # Define the terraform service
    image: hashicorp/terraform:1.6.2 # Use the hashicorp/terraform image with version 1.6.2
    volumes: # Define the volumes that will be mounted to the container, the volumes are the directories that will be used in the pipeline
      - ./setup:/tf/setup # Mount the setup directory to the /tf/setup directory in the container
      - ./deploy:/tf/deploy # Mount the deploy directory to the /tf/deploy directory in the container
    working_dir: /tf # Set the working directory to /tf in the container
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} # AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY are the credentials for the IAM user
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} # that will be used to authenticate the Terraform provider
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN} # AWS_SESSION_TOKEN is the session token that will be used to authenticate the Terraform provider
      - AWS_DEFAULT_REGION=us-east-2 # Set the default region to us-east-2
      - TF_WORKSPACE=${TF_WORKSPACE} # TF_WORKSPACE is the Terraform workspace (environment) that will be used in the pipeline
