# Workflow name
name: Checks

# Trigger of the workflow
# When we create a pull request that targets main it will run this job
on:
  pull_request:
    branches: [main] 

# Jobs that will run in this workflow
jobs:
  test-lint: # id of the job
    name: Test and Lint # user friendly name
    uses: ./.github/workflows/test-and-lint.yml # uses the file to run the job
    secrets:  # secrets that will be used in the job
      DOCKERHUB_USER: ${{ vars.DOCKERHUB_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
